server:
#  port: 8092
 port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: jpc-enrollment-service
  main: # Agrega la propiedad aquí
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/jpc-enrollment
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true






# Configuración de Circuit Breaker con Resilience4j
#resilience4j:
#  circuitbreaker:
#    instances:
#      courseService:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#        permittedNumberOfCallsInHalfOpenState: 3
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10
#      studentService:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#        permittedNumberOfCallsInHalfOpenState: 3
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10
#  timelimiter:
#    instances:
#      courseService:
#        timeoutDuration: 3s
#      studentService:
#        timeoutDuration: 3s
#  retry:
#    instances:
#      courseService:
#        maxAttempts: 3
#        waitDuration: 500ms
#        retryExceptions:
#          - org.springframework.web.client.ResourceAccessException
#          - java.util.concurrent.TimeoutException
#      studentService:
#        maxAttempts: 3
#        waitDuration: 500ms
#        retryExceptions:
#          - org.springframework.web.client.ResourceAccessException
#          - java.util.concurrent.TimeoutException
#








#resilience4j:
#  circuitbreaker:
#    instances:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10
#      courseService:
#        baseConfig: default
#      studentService:
#        baseConfig: default
#
#      instances:
#        courseServiceClient:
#          baseConfig: default
#
#  retry:
#    instances:
#      default:
#        maxAttempts: 3
#        waitDuration: 1s
#        enableExponentialBackoff: true
#        exponentialBackoffMultiplier: 2
#
#  timelimiter:
#    instances:
#      default:
#        timeoutDuration: 2s
#      courseService:
#        timeoutDuration: 1s
#      studentService:
#        timeoutDuration: 1s
#

#
#resilience4j:
#  circuitbreaker:
#    instances:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10
#      courseService:
#        baseConfig: default
#      studentService:
#        baseConfig: default
#      courseServiceClient:
#        baseConfig: default
#
#  retry:
#    instances:
#      default:
#        maxAttempts: 3
#        waitDuration: 1s
#        enableExponentialBackoff: true
#        exponentialBackoffMultiplier: 2
#
#  timelimiter:
#    instances:
#      default:
#        timeoutDuration: 2s
#      courseService:
#        timeoutDuration: 1s
#      studentService:
#        timeoutDuration: 1s


resilience4j:
   circuitbreaker:
     configs:
       default:
         registerHealthIndicator: true
         slidingWindowSize: 10
         minimumNumberOfCalls: 5
         permittedNumberOfCallsInHalfOpenState: 3
         automaticTransitionFromOpenToHalfOpenEnabled: true
         waitDurationInOpenState: 5s
         failureRateThreshold: 50
         eventConsumerBufferSize: 10
     instances:
       courseService:
         baseConfig: default
       studentService:
         baseConfig: default
   retry:
     configs:
       default:
         maxAttempts: 3
         waitDuration: 1s
         enableExponentialBackoff: true
         exponentialBackoffMultiplier: 2
     instances:
       courseService:
         baseConfig: default
       studentService:
         baseConfig: default
   timelimiter:
     configs:
       default:
         timeoutDuration: 2s
     instances:
       courseService:
         baseConfig: default
       studentService:
         baseConfig: default










# Configuración de Actuator para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,retries,timelimiters
  health:
    circuitbreakers:
      enabled: true
    retries:
      enabled: true

  feign:
    circuitbreaker:
      enabled: true





springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
#  instance:
#    hostname: localhost
#
#

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}





