
server:
  port: 8085


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
#      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
#  instance:
#    hostname: localhost
#    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#spring:

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria/**

        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/pedido/**


        - id: ms-pago-service
          uri: lb://ms-pago-service
          predicates:
            - Path=/pago/**

        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/cliente/**





        - id: jpc-course-service
          uri: lb://jpc-course-service
          predicates:
            - Path=/api/courses/**
          filters:
            - AuthFilter


        - id: jpc-enrollment-service
          uri: lb://jpc-enrollment-service
          predicates:
            - Path=/api/enrollments/**
          filters:
            - AuthFilter


        - id: jpc-student-service
          uri: lb://jpc-student-service
          predicates:
            - Path=/api/students/**


        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

